spring:
    application:
        name: ecommerce

    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce
        username: cherel
        password: l@o_nel_123
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect  

    mvc:
        servlet:
            path: /api/v1  


logging:
    level:
        com:
            ecommerce : DEBUG
        org:
            springframework : INFO
            hibernate : WARN


    file: 
        name: application.log


    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"





