spring:
    application:
        name: ecommerce

    datasource:
        url: jdbc:mysql://localhost:3306/ecommerce
        username: cherel
        password: l@o_nel_123
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect  

    security:
        user:
            name: cherel
            password: l@o_nel_123

    mvc.servlet.path: /api/v1  

jwt:
    secret : je suis developper backend
    expirationMs : 86400000 # un jour




logging:
    level:
        com:
            ecommerce : DEBUG
        root: INFO
        org:
            springframework : INFO
            hibernate : WARN


    file: 
        name: application.log


    pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"


springdoc:
  api-docs:
    path: /v3/api-docs        
  swagger-ui:
    path: /swagger-ui.html    
  packages-to-scan: 
        - cm.backend.ecommerce.controllers




